# Generated by Django 4.2.7 on 2024-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog_add",
            name="blog_title",
            field=models.CharField(max_length=26, null=True),
        ),
    ]
