# Generated by Django 4.2.7 on 2024-03-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_add_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog_add",
            name="blog_description",
            field=models.TextField(blank=True),
        ),
    ]
