# Generated by Django 4.2.7 on 2024-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_add_blog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog_add",
            name="image",
            field=models.FileField(blank=True, upload_to="static/images/blog/"),
        ),
    ]
