# Generated by Django 4.1.7 on 2023-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namebatch", models.CharField(max_length=26)),
                ("stylebatch", models.CharField(max_length=26)),
                ("ogbatch", models.FloatField(max_length=4)),
                ("abvbatch", models.FloatField(max_length=4)),
                ("ibubatch", models.FloatField(max_length=4)),
            ],
        ),
    ]
