# Generated by Django 4.2.7 on 2024-02-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="image",
            field=models.FileField(blank=True, upload_to="static/images/"),
        ),
    ]
