# Generated by Django 4.2.7 on 2024-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batches", "0002_batch_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="image",
            field=models.FileField(blank=True, upload_to="static/images/batches/"),
        ),
    ]
